import { defineConfig } from 'vitepress'
import { withSidebar } from 'vitepress-sidebar';
import mathjax3 from 'markdown-it-mathjax3';

const vitePressOptions = {
  lang: "zh-CN",
  title: "集成全家桶",
  description: "一个面向南京大学集成电路学院同学的民间Wiki",
  markdown: {
    config: (md) => {
      md.use(mathjax3);
    },
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith('mjx-'),
      },
    },
  },
  // rewrites(id: string) {
  //   return id.replace(/(^|\/)\d+\-/g, '$1');
  // },
  lastUpdated: true,
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    search: {
      provider: 'local'
    },
    nav: [
      { text: '博客', link: '/1-基础篇/1-博客简介' },
      { text: '贡献指南', link: '/7-贡献篇/1-贡献指南' },
      { text: 'GitHub', link: 'https://github.com/njuic-students/njuic-students.github.io' }
    ],

    // Sidebar will be generated by `vitepress-sidebar` plugin

    socialLinks: [
      { icon: 'github', link: 'https://github.com/njuic-students' }
    ]
  }
};

const vitePressSidebarOptions = {
  // VitePress Sidebar's options here...
  // project docs folder (per plugin docs should be '/docs' if docs is under project root)
  documentRootPath: '/docs',
  collapsed: true,
  collapseDepth: 2,
  capitalizeFirst: true,
  // useTitleFromFrontmatter: true,
  sortMenusOrderNumericallyFromTitle: true,
  sortMenusOrderByDescending: false,
  removePrefixAfterOrdering: true,
  prefixSeparator: '-',
  // enable debug printing to see generated sidebar in console
  debugPrint: true
  // useFolderTitleFromIndexFile: true
  // sortMenusByFrontmatterOrder: true,
  // frontmatterOrderDefaultValue: 999,
  // manualSortFileNameByPriority:  [
  //   "基础篇",
  //   "学习篇",
  //   "科研篇",
  //   "职场篇",
  //   "生活篇",
  //   "FAQ",
  //   "贡献篇"
  // ]
};


// https://vitepress.dev/reference/site-config
export default defineConfig(
  withSidebar(vitePressOptions, vitePressSidebarOptions)
)
